// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: audit.proto

package controlv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AuditEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TsUnixMs      int64                  `protobuf:"varint,1,opt,name=ts_unix_ms,json=tsUnixMs,proto3" json:"ts_unix_ms,omitempty"`
	Tenant        string                 `protobuf:"bytes,2,opt,name=tenant,proto3" json:"tenant,omitempty"`
	Caller        string                 `protobuf:"bytes,3,opt,name=caller,proto3" json:"caller,omitempty"`
	Target        string                 `protobuf:"bytes,4,opt,name=target,proto3" json:"target,omitempty"`
	Method        string                 `protobuf:"bytes,5,opt,name=method,proto3" json:"method,omitempty"`
	Decision      Decision               `protobuf:"varint,6,opt,name=decision,proto3,enum=outrelay.control.v1.Decision" json:"decision,omitempty"`
	Reason        string                 `protobuf:"bytes,7,opt,name=reason,proto3" json:"reason,omitempty"`
	StreamId      string                 `protobuf:"bytes,8,opt,name=stream_id,json=streamId,proto3" json:"stream_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AuditEvent) Reset() {
	*x = AuditEvent{}
	mi := &file_audit_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuditEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuditEvent) ProtoMessage() {}

func (x *AuditEvent) ProtoReflect() protoreflect.Message {
	mi := &file_audit_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuditEvent.ProtoReflect.Descriptor instead.
func (*AuditEvent) Descriptor() ([]byte, []int) {
	return file_audit_proto_rawDescGZIP(), []int{0}
}

func (x *AuditEvent) GetTsUnixMs() int64 {
	if x != nil {
		return x.TsUnixMs
	}
	return 0
}

func (x *AuditEvent) GetTenant() string {
	if x != nil {
		return x.Tenant
	}
	return ""
}

func (x *AuditEvent) GetCaller() string {
	if x != nil {
		return x.Caller
	}
	return ""
}

func (x *AuditEvent) GetTarget() string {
	if x != nil {
		return x.Target
	}
	return ""
}

func (x *AuditEvent) GetMethod() string {
	if x != nil {
		return x.Method
	}
	return ""
}

func (x *AuditEvent) GetDecision() Decision {
	if x != nil {
		return x.Decision
	}
	return Decision_DECISION_UNSPECIFIED
}

func (x *AuditEvent) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

func (x *AuditEvent) GetStreamId() string {
	if x != nil {
		return x.StreamId
	}
	return ""
}

type RecordAuditRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Event         *AuditEvent            `protobuf:"bytes,1,opt,name=event,proto3" json:"event,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RecordAuditRequest) Reset() {
	*x = RecordAuditRequest{}
	mi := &file_audit_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RecordAuditRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RecordAuditRequest) ProtoMessage() {}

func (x *RecordAuditRequest) ProtoReflect() protoreflect.Message {
	mi := &file_audit_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RecordAuditRequest.ProtoReflect.Descriptor instead.
func (*RecordAuditRequest) Descriptor() ([]byte, []int) {
	return file_audit_proto_rawDescGZIP(), []int{1}
}

func (x *RecordAuditRequest) GetEvent() *AuditEvent {
	if x != nil {
		return x.Event
	}
	return nil
}

type RecordAuditResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RecordAuditResponse) Reset() {
	*x = RecordAuditResponse{}
	mi := &file_audit_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RecordAuditResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RecordAuditResponse) ProtoMessage() {}

func (x *RecordAuditResponse) ProtoReflect() protoreflect.Message {
	mi := &file_audit_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RecordAuditResponse.ProtoReflect.Descriptor instead.
func (*RecordAuditResponse) Descriptor() ([]byte, []int) {
	return file_audit_proto_rawDescGZIP(), []int{2}
}

type QueryAuditRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Tenant        string                 `protobuf:"bytes,1,opt,name=tenant,proto3" json:"tenant,omitempty"`
	Caller        string                 `protobuf:"bytes,2,opt,name=caller,proto3" json:"caller,omitempty"`                                 // optional exact match
	Target        string                 `protobuf:"bytes,3,opt,name=target,proto3" json:"target,omitempty"`                                 // optional exact match
	SinceUnixMs   int64                  `protobuf:"varint,4,opt,name=since_unix_ms,json=sinceUnixMs,proto3" json:"since_unix_ms,omitempty"` // 0 = no lower bound
	Limit         int32                  `protobuf:"varint,5,opt,name=limit,proto3" json:"limit,omitempty"`                                  // 0 = no cap
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueryAuditRequest) Reset() {
	*x = QueryAuditRequest{}
	mi := &file_audit_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryAuditRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryAuditRequest) ProtoMessage() {}

func (x *QueryAuditRequest) ProtoReflect() protoreflect.Message {
	mi := &file_audit_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryAuditRequest.ProtoReflect.Descriptor instead.
func (*QueryAuditRequest) Descriptor() ([]byte, []int) {
	return file_audit_proto_rawDescGZIP(), []int{3}
}

func (x *QueryAuditRequest) GetTenant() string {
	if x != nil {
		return x.Tenant
	}
	return ""
}

func (x *QueryAuditRequest) GetCaller() string {
	if x != nil {
		return x.Caller
	}
	return ""
}

func (x *QueryAuditRequest) GetTarget() string {
	if x != nil {
		return x.Target
	}
	return ""
}

func (x *QueryAuditRequest) GetSinceUnixMs() int64 {
	if x != nil {
		return x.SinceUnixMs
	}
	return 0
}

func (x *QueryAuditRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

var File_audit_proto protoreflect.FileDescriptor

const file_audit_proto_rawDesc = "" +
	"\n" +
	"\vaudit.proto\x12\x13outrelay.control.v1\x1a\fpolicy.proto\"\xfa\x01\n" +
	"\n" +
	"AuditEvent\x12\x1c\n" +
	"\n" +
	"ts_unix_ms\x18\x01 \x01(\x03R\btsUnixMs\x12\x16\n" +
	"\x06tenant\x18\x02 \x01(\tR\x06tenant\x12\x16\n" +
	"\x06caller\x18\x03 \x01(\tR\x06caller\x12\x16\n" +
	"\x06target\x18\x04 \x01(\tR\x06target\x12\x16\n" +
	"\x06method\x18\x05 \x01(\tR\x06method\x129\n" +
	"\bdecision\x18\x06 \x01(\x0e2\x1d.outrelay.control.v1.DecisionR\bdecision\x12\x16\n" +
	"\x06reason\x18\a \x01(\tR\x06reason\x12\x1b\n" +
	"\tstream_id\x18\b \x01(\tR\bstreamId\"K\n" +
	"\x12RecordAuditRequest\x125\n" +
	"\x05event\x18\x01 \x01(\v2\x1f.outrelay.control.v1.AuditEventR\x05event\"\x15\n" +
	"\x13RecordAuditResponse\"\x95\x01\n" +
	"\x11QueryAuditRequest\x12\x16\n" +
	"\x06tenant\x18\x01 \x01(\tR\x06tenant\x12\x16\n" +
	"\x06caller\x18\x02 \x01(\tR\x06caller\x12\x16\n" +
	"\x06target\x18\x03 \x01(\tR\x06target\x12\"\n" +
	"\rsince_unix_ms\x18\x04 \x01(\x03R\vsinceUnixMs\x12\x14\n" +
	"\x05limit\x18\x05 \x01(\x05R\x05limit2\xb8\x01\n" +
	"\x05Audit\x12[\n" +
	"\x06Record\x12'.outrelay.control.v1.RecordAuditRequest\x1a(.outrelay.control.v1.RecordAuditResponse\x12R\n" +
	"\x05Query\x12&.outrelay.control.v1.QueryAuditRequest\x1a\x1f.outrelay.control.v1.AuditEvent0\x01B6Z4github.com/boanlab/OutRelay/lib/control/v1;controlv1b\x06proto3"

var (
	file_audit_proto_rawDescOnce sync.Once
	file_audit_proto_rawDescData []byte
)

func file_audit_proto_rawDescGZIP() []byte {
	file_audit_proto_rawDescOnce.Do(func() {
		file_audit_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_audit_proto_rawDesc), len(file_audit_proto_rawDesc)))
	})
	return file_audit_proto_rawDescData
}

var file_audit_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_audit_proto_goTypes = []any{
	(*AuditEvent)(nil),          // 0: outrelay.control.v1.AuditEvent
	(*RecordAuditRequest)(nil),  // 1: outrelay.control.v1.RecordAuditRequest
	(*RecordAuditResponse)(nil), // 2: outrelay.control.v1.RecordAuditResponse
	(*QueryAuditRequest)(nil),   // 3: outrelay.control.v1.QueryAuditRequest
	(Decision)(0),               // 4: outrelay.control.v1.Decision
}
var file_audit_proto_depIdxs = []int32{
	4, // 0: outrelay.control.v1.AuditEvent.decision:type_name -> outrelay.control.v1.Decision
	0, // 1: outrelay.control.v1.RecordAuditRequest.event:type_name -> outrelay.control.v1.AuditEvent
	1, // 2: outrelay.control.v1.Audit.Record:input_type -> outrelay.control.v1.RecordAuditRequest
	3, // 3: outrelay.control.v1.Audit.Query:input_type -> outrelay.control.v1.QueryAuditRequest
	2, // 4: outrelay.control.v1.Audit.Record:output_type -> outrelay.control.v1.RecordAuditResponse
	0, // 5: outrelay.control.v1.Audit.Query:output_type -> outrelay.control.v1.AuditEvent
	4, // [4:6] is the sub-list for method output_type
	2, // [2:4] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_audit_proto_init() }
func file_audit_proto_init() {
	if File_audit_proto != nil {
		return
	}
	file_policy_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_audit_proto_rawDesc), len(file_audit_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_audit_proto_goTypes,
		DependencyIndexes: file_audit_proto_depIdxs,
		MessageInfos:      file_audit_proto_msgTypes,
	}.Build()
	File_audit_proto = out.File
	file_audit_proto_goTypes = nil
	file_audit_proto_depIdxs = nil
}
