// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: policy.proto

package controlv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Decision int32

const (
	Decision_DECISION_UNSPECIFIED Decision = 0
	Decision_DECISION_ALLOW       Decision = 1
	Decision_DECISION_DENY        Decision = 2
)

// Enum value maps for Decision.
var (
	Decision_name = map[int32]string{
		0: "DECISION_UNSPECIFIED",
		1: "DECISION_ALLOW",
		2: "DECISION_DENY",
	}
	Decision_value = map[string]int32{
		"DECISION_UNSPECIFIED": 0,
		"DECISION_ALLOW":       1,
		"DECISION_DENY":        2,
	}
)

func (x Decision) Enum() *Decision {
	p := new(Decision)
	*p = x
	return p
}

func (x Decision) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Decision) Descriptor() protoreflect.EnumDescriptor {
	return file_policy_proto_enumTypes[0].Descriptor()
}

func (Decision) Type() protoreflect.EnumType {
	return &file_policy_proto_enumTypes[0]
}

func (x Decision) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Decision.Descriptor instead.
func (Decision) EnumDescriptor() ([]byte, []int) {
	return file_policy_proto_rawDescGZIP(), []int{0}
}

// P2PMode controls whether streams matching this rule are eligible
// for P2P (direct agent-to-agent) promotion.
type P2PMode int32

const (
	// P2P_ALLOWED: opportunistic. The default — try promotion in the
	// background, fall back to relay on failure.
	P2PMode_P2P_ALLOWED P2PMode = 0
	// P2P_FORBIDDEN: never attempt. All bytes flow through the relay
	// so audit / metering can observe them.
	P2PMode_P2P_FORBIDDEN P2PMode = 1
	// P2P_REQUIRED: stream open is rejected if P2P cannot be
	// established. Use for channels where relay terminations are a
	// security concern (e.g. plaintext key exchange).
	P2PMode_P2P_REQUIRED P2PMode = 2
)

// Enum value maps for P2PMode.
var (
	P2PMode_name = map[int32]string{
		0: "P2P_ALLOWED",
		1: "P2P_FORBIDDEN",
		2: "P2P_REQUIRED",
	}
	P2PMode_value = map[string]int32{
		"P2P_ALLOWED":   0,
		"P2P_FORBIDDEN": 1,
		"P2P_REQUIRED":  2,
	}
)

func (x P2PMode) Enum() *P2PMode {
	p := new(P2PMode)
	*p = x
	return p
}

func (x P2PMode) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (P2PMode) Descriptor() protoreflect.EnumDescriptor {
	return file_policy_proto_enumTypes[1].Descriptor()
}

func (P2PMode) Type() protoreflect.EnumType {
	return &file_policy_proto_enumTypes[1]
}

func (x P2PMode) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use P2PMode.Descriptor instead.
func (P2PMode) EnumDescriptor() ([]byte, []int) {
	return file_policy_proto_rawDescGZIP(), []int{1}
}

type PolicyEvent_Kind int32

const (
	PolicyEvent_POLICY_KIND_UNSPECIFIED PolicyEvent_Kind = 0
	PolicyEvent_POLICY_KIND_ADDED       PolicyEvent_Kind = 1
	PolicyEvent_POLICY_KIND_REMOVED     PolicyEvent_Kind = 2
	// SNAPSHOT_END marks the end of the initial bulk send so the
	// relay can flip to "live" mode.
	PolicyEvent_POLICY_KIND_SNAPSHOT_END PolicyEvent_Kind = 3
)

// Enum value maps for PolicyEvent_Kind.
var (
	PolicyEvent_Kind_name = map[int32]string{
		0: "POLICY_KIND_UNSPECIFIED",
		1: "POLICY_KIND_ADDED",
		2: "POLICY_KIND_REMOVED",
		3: "POLICY_KIND_SNAPSHOT_END",
	}
	PolicyEvent_Kind_value = map[string]int32{
		"POLICY_KIND_UNSPECIFIED":  0,
		"POLICY_KIND_ADDED":        1,
		"POLICY_KIND_REMOVED":      2,
		"POLICY_KIND_SNAPSHOT_END": 3,
	}
)

func (x PolicyEvent_Kind) Enum() *PolicyEvent_Kind {
	p := new(PolicyEvent_Kind)
	*p = x
	return p
}

func (x PolicyEvent_Kind) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (PolicyEvent_Kind) Descriptor() protoreflect.EnumDescriptor {
	return file_policy_proto_enumTypes[2].Descriptor()
}

func (PolicyEvent_Kind) Type() protoreflect.EnumType {
	return &file_policy_proto_enumTypes[2]
}

func (x PolicyEvent_Kind) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use PolicyEvent_Kind.Descriptor instead.
func (PolicyEvent_Kind) EnumDescriptor() ([]byte, []int) {
	return file_policy_proto_rawDescGZIP(), []int{8, 0}
}

type PolicyRule struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Id              string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Tenant          string                 `protobuf:"bytes,2,opt,name=tenant,proto3" json:"tenant,omitempty"`
	CallerPattern   string                 `protobuf:"bytes,3,opt,name=caller_pattern,json=callerPattern,proto3" json:"caller_pattern,omitempty"` // glob: outrelay://acme/svc-* or exact URI
	TargetPattern   string                 `protobuf:"bytes,4,opt,name=target_pattern,json=targetPattern,proto3" json:"target_pattern,omitempty"` // glob: svc-* or exact name
	MethodPattern   string                 `protobuf:"bytes,5,opt,name=method_pattern,json=methodPattern,proto3" json:"method_pattern,omitempty"` // glob: "POST /charge" or "POST *" (empty = match all)
	Decision        Decision               `protobuf:"varint,6,opt,name=decision,proto3,enum=outrelay.control.v1.Decision" json:"decision,omitempty"`
	ExpiresUnixMs   int64                  `protobuf:"varint,7,opt,name=expires_unix_ms,json=expiresUnixMs,proto3" json:"expires_unix_ms,omitempty"` // 0 = never expires
	CreatedAtUnixMs int64                  `protobuf:"varint,8,opt,name=created_at_unix_ms,json=createdAtUnixMs,proto3" json:"created_at_unix_ms,omitempty"`
	P2PMode         P2PMode                `protobuf:"varint,9,opt,name=p2p_mode,json=p2pMode,proto3,enum=outrelay.control.v1.P2PMode" json:"p2p_mode,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *PolicyRule) Reset() {
	*x = PolicyRule{}
	mi := &file_policy_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PolicyRule) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PolicyRule) ProtoMessage() {}

func (x *PolicyRule) ProtoReflect() protoreflect.Message {
	mi := &file_policy_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PolicyRule.ProtoReflect.Descriptor instead.
func (*PolicyRule) Descriptor() ([]byte, []int) {
	return file_policy_proto_rawDescGZIP(), []int{0}
}

func (x *PolicyRule) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *PolicyRule) GetTenant() string {
	if x != nil {
		return x.Tenant
	}
	return ""
}

func (x *PolicyRule) GetCallerPattern() string {
	if x != nil {
		return x.CallerPattern
	}
	return ""
}

func (x *PolicyRule) GetTargetPattern() string {
	if x != nil {
		return x.TargetPattern
	}
	return ""
}

func (x *PolicyRule) GetMethodPattern() string {
	if x != nil {
		return x.MethodPattern
	}
	return ""
}

func (x *PolicyRule) GetDecision() Decision {
	if x != nil {
		return x.Decision
	}
	return Decision_DECISION_UNSPECIFIED
}

func (x *PolicyRule) GetExpiresUnixMs() int64 {
	if x != nil {
		return x.ExpiresUnixMs
	}
	return 0
}

func (x *PolicyRule) GetCreatedAtUnixMs() int64 {
	if x != nil {
		return x.CreatedAtUnixMs
	}
	return 0
}

func (x *PolicyRule) GetP2PMode() P2PMode {
	if x != nil {
		return x.P2PMode
	}
	return P2PMode_P2P_ALLOWED
}

type AddPolicyRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Rule          *PolicyRule            `protobuf:"bytes,1,opt,name=rule,proto3" json:"rule,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddPolicyRequest) Reset() {
	*x = AddPolicyRequest{}
	mi := &file_policy_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddPolicyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddPolicyRequest) ProtoMessage() {}

func (x *AddPolicyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_policy_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddPolicyRequest.ProtoReflect.Descriptor instead.
func (*AddPolicyRequest) Descriptor() ([]byte, []int) {
	return file_policy_proto_rawDescGZIP(), []int{1}
}

func (x *AddPolicyRequest) GetRule() *PolicyRule {
	if x != nil {
		return x.Rule
	}
	return nil
}

type AddPolicyResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddPolicyResponse) Reset() {
	*x = AddPolicyResponse{}
	mi := &file_policy_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddPolicyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddPolicyResponse) ProtoMessage() {}

func (x *AddPolicyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_policy_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddPolicyResponse.ProtoReflect.Descriptor instead.
func (*AddPolicyResponse) Descriptor() ([]byte, []int) {
	return file_policy_proto_rawDescGZIP(), []int{2}
}

func (x *AddPolicyResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type RemovePolicyRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Tenant        string                 `protobuf:"bytes,1,opt,name=tenant,proto3" json:"tenant,omitempty"`
	Id            string                 `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RemovePolicyRequest) Reset() {
	*x = RemovePolicyRequest{}
	mi := &file_policy_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemovePolicyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemovePolicyRequest) ProtoMessage() {}

func (x *RemovePolicyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_policy_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemovePolicyRequest.ProtoReflect.Descriptor instead.
func (*RemovePolicyRequest) Descriptor() ([]byte, []int) {
	return file_policy_proto_rawDescGZIP(), []int{3}
}

func (x *RemovePolicyRequest) GetTenant() string {
	if x != nil {
		return x.Tenant
	}
	return ""
}

func (x *RemovePolicyRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type RemovePolicyResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Removed       bool                   `protobuf:"varint,1,opt,name=removed,proto3" json:"removed,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RemovePolicyResponse) Reset() {
	*x = RemovePolicyResponse{}
	mi := &file_policy_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemovePolicyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemovePolicyResponse) ProtoMessage() {}

func (x *RemovePolicyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_policy_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemovePolicyResponse.ProtoReflect.Descriptor instead.
func (*RemovePolicyResponse) Descriptor() ([]byte, []int) {
	return file_policy_proto_rawDescGZIP(), []int{4}
}

func (x *RemovePolicyResponse) GetRemoved() bool {
	if x != nil {
		return x.Removed
	}
	return false
}

type ListPoliciesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Tenant        string                 `protobuf:"bytes,1,opt,name=tenant,proto3" json:"tenant,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListPoliciesRequest) Reset() {
	*x = ListPoliciesRequest{}
	mi := &file_policy_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListPoliciesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListPoliciesRequest) ProtoMessage() {}

func (x *ListPoliciesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_policy_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListPoliciesRequest.ProtoReflect.Descriptor instead.
func (*ListPoliciesRequest) Descriptor() ([]byte, []int) {
	return file_policy_proto_rawDescGZIP(), []int{5}
}

func (x *ListPoliciesRequest) GetTenant() string {
	if x != nil {
		return x.Tenant
	}
	return ""
}

type ListPoliciesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Rules         []*PolicyRule          `protobuf:"bytes,1,rep,name=rules,proto3" json:"rules,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListPoliciesResponse) Reset() {
	*x = ListPoliciesResponse{}
	mi := &file_policy_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListPoliciesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListPoliciesResponse) ProtoMessage() {}

func (x *ListPoliciesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_policy_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListPoliciesResponse.ProtoReflect.Descriptor instead.
func (*ListPoliciesResponse) Descriptor() ([]byte, []int) {
	return file_policy_proto_rawDescGZIP(), []int{6}
}

func (x *ListPoliciesResponse) GetRules() []*PolicyRule {
	if x != nil {
		return x.Rules
	}
	return nil
}

type WatchPoliciesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Tenant        string                 `protobuf:"bytes,1,opt,name=tenant,proto3" json:"tenant,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WatchPoliciesRequest) Reset() {
	*x = WatchPoliciesRequest{}
	mi := &file_policy_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WatchPoliciesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WatchPoliciesRequest) ProtoMessage() {}

func (x *WatchPoliciesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_policy_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WatchPoliciesRequest.ProtoReflect.Descriptor instead.
func (*WatchPoliciesRequest) Descriptor() ([]byte, []int) {
	return file_policy_proto_rawDescGZIP(), []int{7}
}

func (x *WatchPoliciesRequest) GetTenant() string {
	if x != nil {
		return x.Tenant
	}
	return ""
}

type PolicyEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Kind          PolicyEvent_Kind       `protobuf:"varint,1,opt,name=kind,proto3,enum=outrelay.control.v1.PolicyEvent_Kind" json:"kind,omitempty"`
	Rule          *PolicyRule            `protobuf:"bytes,2,opt,name=rule,proto3" json:"rule,omitempty"`
	RemovedId     string                 `protobuf:"bytes,3,opt,name=removed_id,json=removedId,proto3" json:"removed_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PolicyEvent) Reset() {
	*x = PolicyEvent{}
	mi := &file_policy_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PolicyEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PolicyEvent) ProtoMessage() {}

func (x *PolicyEvent) ProtoReflect() protoreflect.Message {
	mi := &file_policy_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PolicyEvent.ProtoReflect.Descriptor instead.
func (*PolicyEvent) Descriptor() ([]byte, []int) {
	return file_policy_proto_rawDescGZIP(), []int{8}
}

func (x *PolicyEvent) GetKind() PolicyEvent_Kind {
	if x != nil {
		return x.Kind
	}
	return PolicyEvent_POLICY_KIND_UNSPECIFIED
}

func (x *PolicyEvent) GetRule() *PolicyRule {
	if x != nil {
		return x.Rule
	}
	return nil
}

func (x *PolicyEvent) GetRemovedId() string {
	if x != nil {
		return x.RemovedId
	}
	return ""
}

var File_policy_proto protoreflect.FileDescriptor

const file_policy_proto_rawDesc = "" +
	"\n" +
	"\fpolicy.proto\x12\x13outrelay.control.v1\"\xf2\x02\n" +
	"\n" +
	"PolicyRule\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x16\n" +
	"\x06tenant\x18\x02 \x01(\tR\x06tenant\x12%\n" +
	"\x0ecaller_pattern\x18\x03 \x01(\tR\rcallerPattern\x12%\n" +
	"\x0etarget_pattern\x18\x04 \x01(\tR\rtargetPattern\x12%\n" +
	"\x0emethod_pattern\x18\x05 \x01(\tR\rmethodPattern\x129\n" +
	"\bdecision\x18\x06 \x01(\x0e2\x1d.outrelay.control.v1.DecisionR\bdecision\x12&\n" +
	"\x0fexpires_unix_ms\x18\a \x01(\x03R\rexpiresUnixMs\x12+\n" +
	"\x12created_at_unix_ms\x18\b \x01(\x03R\x0fcreatedAtUnixMs\x127\n" +
	"\bp2p_mode\x18\t \x01(\x0e2\x1c.outrelay.control.v1.P2PModeR\ap2pMode\"G\n" +
	"\x10AddPolicyRequest\x123\n" +
	"\x04rule\x18\x01 \x01(\v2\x1f.outrelay.control.v1.PolicyRuleR\x04rule\"#\n" +
	"\x11AddPolicyResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"=\n" +
	"\x13RemovePolicyRequest\x12\x16\n" +
	"\x06tenant\x18\x01 \x01(\tR\x06tenant\x12\x0e\n" +
	"\x02id\x18\x02 \x01(\tR\x02id\"0\n" +
	"\x14RemovePolicyResponse\x12\x18\n" +
	"\aremoved\x18\x01 \x01(\bR\aremoved\"-\n" +
	"\x13ListPoliciesRequest\x12\x16\n" +
	"\x06tenant\x18\x01 \x01(\tR\x06tenant\"M\n" +
	"\x14ListPoliciesResponse\x125\n" +
	"\x05rules\x18\x01 \x03(\v2\x1f.outrelay.control.v1.PolicyRuleR\x05rules\".\n" +
	"\x14WatchPoliciesRequest\x12\x16\n" +
	"\x06tenant\x18\x01 \x01(\tR\x06tenant\"\x8f\x02\n" +
	"\vPolicyEvent\x129\n" +
	"\x04kind\x18\x01 \x01(\x0e2%.outrelay.control.v1.PolicyEvent.KindR\x04kind\x123\n" +
	"\x04rule\x18\x02 \x01(\v2\x1f.outrelay.control.v1.PolicyRuleR\x04rule\x12\x1d\n" +
	"\n" +
	"removed_id\x18\x03 \x01(\tR\tremovedId\"q\n" +
	"\x04Kind\x12\x1b\n" +
	"\x17POLICY_KIND_UNSPECIFIED\x10\x00\x12\x15\n" +
	"\x11POLICY_KIND_ADDED\x10\x01\x12\x17\n" +
	"\x13POLICY_KIND_REMOVED\x10\x02\x12\x1c\n" +
	"\x18POLICY_KIND_SNAPSHOT_END\x10\x03*K\n" +
	"\bDecision\x12\x18\n" +
	"\x14DECISION_UNSPECIFIED\x10\x00\x12\x12\n" +
	"\x0eDECISION_ALLOW\x10\x01\x12\x11\n" +
	"\rDECISION_DENY\x10\x02*?\n" +
	"\aP2PMode\x12\x0f\n" +
	"\vP2P_ALLOWED\x10\x00\x12\x11\n" +
	"\rP2P_FORBIDDEN\x10\x01\x12\x10\n" +
	"\fP2P_REQUIRED\x10\x022\x86\x03\n" +
	"\x06Policy\x12Z\n" +
	"\tAddPolicy\x12%.outrelay.control.v1.AddPolicyRequest\x1a&.outrelay.control.v1.AddPolicyResponse\x12c\n" +
	"\fRemovePolicy\x12(.outrelay.control.v1.RemovePolicyRequest\x1a).outrelay.control.v1.RemovePolicyResponse\x12c\n" +
	"\fListPolicies\x12(.outrelay.control.v1.ListPoliciesRequest\x1a).outrelay.control.v1.ListPoliciesResponse\x12V\n" +
	"\x05Watch\x12).outrelay.control.v1.WatchPoliciesRequest\x1a .outrelay.control.v1.PolicyEvent0\x01B6Z4github.com/boanlab/OutRelay/lib/control/v1;controlv1b\x06proto3"

var (
	file_policy_proto_rawDescOnce sync.Once
	file_policy_proto_rawDescData []byte
)

func file_policy_proto_rawDescGZIP() []byte {
	file_policy_proto_rawDescOnce.Do(func() {
		file_policy_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_policy_proto_rawDesc), len(file_policy_proto_rawDesc)))
	})
	return file_policy_proto_rawDescData
}

var file_policy_proto_enumTypes = make([]protoimpl.EnumInfo, 3)
var file_policy_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_policy_proto_goTypes = []any{
	(Decision)(0),                // 0: outrelay.control.v1.Decision
	(P2PMode)(0),                 // 1: outrelay.control.v1.P2PMode
	(PolicyEvent_Kind)(0),        // 2: outrelay.control.v1.PolicyEvent.Kind
	(*PolicyRule)(nil),           // 3: outrelay.control.v1.PolicyRule
	(*AddPolicyRequest)(nil),     // 4: outrelay.control.v1.AddPolicyRequest
	(*AddPolicyResponse)(nil),    // 5: outrelay.control.v1.AddPolicyResponse
	(*RemovePolicyRequest)(nil),  // 6: outrelay.control.v1.RemovePolicyRequest
	(*RemovePolicyResponse)(nil), // 7: outrelay.control.v1.RemovePolicyResponse
	(*ListPoliciesRequest)(nil),  // 8: outrelay.control.v1.ListPoliciesRequest
	(*ListPoliciesResponse)(nil), // 9: outrelay.control.v1.ListPoliciesResponse
	(*WatchPoliciesRequest)(nil), // 10: outrelay.control.v1.WatchPoliciesRequest
	(*PolicyEvent)(nil),          // 11: outrelay.control.v1.PolicyEvent
}
var file_policy_proto_depIdxs = []int32{
	0,  // 0: outrelay.control.v1.PolicyRule.decision:type_name -> outrelay.control.v1.Decision
	1,  // 1: outrelay.control.v1.PolicyRule.p2p_mode:type_name -> outrelay.control.v1.P2PMode
	3,  // 2: outrelay.control.v1.AddPolicyRequest.rule:type_name -> outrelay.control.v1.PolicyRule
	3,  // 3: outrelay.control.v1.ListPoliciesResponse.rules:type_name -> outrelay.control.v1.PolicyRule
	2,  // 4: outrelay.control.v1.PolicyEvent.kind:type_name -> outrelay.control.v1.PolicyEvent.Kind
	3,  // 5: outrelay.control.v1.PolicyEvent.rule:type_name -> outrelay.control.v1.PolicyRule
	4,  // 6: outrelay.control.v1.Policy.AddPolicy:input_type -> outrelay.control.v1.AddPolicyRequest
	6,  // 7: outrelay.control.v1.Policy.RemovePolicy:input_type -> outrelay.control.v1.RemovePolicyRequest
	8,  // 8: outrelay.control.v1.Policy.ListPolicies:input_type -> outrelay.control.v1.ListPoliciesRequest
	10, // 9: outrelay.control.v1.Policy.Watch:input_type -> outrelay.control.v1.WatchPoliciesRequest
	5,  // 10: outrelay.control.v1.Policy.AddPolicy:output_type -> outrelay.control.v1.AddPolicyResponse
	7,  // 11: outrelay.control.v1.Policy.RemovePolicy:output_type -> outrelay.control.v1.RemovePolicyResponse
	9,  // 12: outrelay.control.v1.Policy.ListPolicies:output_type -> outrelay.control.v1.ListPoliciesResponse
	11, // 13: outrelay.control.v1.Policy.Watch:output_type -> outrelay.control.v1.PolicyEvent
	10, // [10:14] is the sub-list for method output_type
	6,  // [6:10] is the sub-list for method input_type
	6,  // [6:6] is the sub-list for extension type_name
	6,  // [6:6] is the sub-list for extension extendee
	0,  // [0:6] is the sub-list for field type_name
}

func init() { file_policy_proto_init() }
func file_policy_proto_init() {
	if File_policy_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_policy_proto_rawDesc), len(file_policy_proto_rawDesc)),
			NumEnums:      3,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_policy_proto_goTypes,
		DependencyIndexes: file_policy_proto_depIdxs,
		EnumInfos:         file_policy_proto_enumTypes,
		MessageInfos:      file_policy_proto_msgTypes,
	}.Build()
	File_policy_proto = out.File
	file_policy_proto_goTypes = nil
	file_policy_proto_depIdxs = nil
}
