// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: registry.proto

package controlv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type EventKind int32

const (
	EventKind_EVENT_KIND_UNSPECIFIED EventKind = 0
	EventKind_EVENT_KIND_REGISTER    EventKind = 1
	EventKind_EVENT_KIND_DEREGISTER  EventKind = 2
)

// Enum value maps for EventKind.
var (
	EventKind_name = map[int32]string{
		0: "EVENT_KIND_UNSPECIFIED",
		1: "EVENT_KIND_REGISTER",
		2: "EVENT_KIND_DEREGISTER",
	}
	EventKind_value = map[string]int32{
		"EVENT_KIND_UNSPECIFIED": 0,
		"EVENT_KIND_REGISTER":    1,
		"EVENT_KIND_DEREGISTER":  2,
	}
)

func (x EventKind) Enum() *EventKind {
	p := new(EventKind)
	*p = x
	return p
}

func (x EventKind) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (EventKind) Descriptor() protoreflect.EnumDescriptor {
	return file_registry_proto_enumTypes[0].Descriptor()
}

func (EventKind) Type() protoreflect.EnumType {
	return &file_registry_proto_enumTypes[0]
}

func (x EventKind) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use EventKind.Descriptor instead.
func (EventKind) EnumDescriptor() ([]byte, []int) {
	return file_registry_proto_rawDescGZIP(), []int{0}
}

type RegisterServiceRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Tenant        string                 `protobuf:"bytes,1,opt,name=tenant,proto3" json:"tenant,omitempty"`
	ServiceName   string                 `protobuf:"bytes,2,opt,name=service_name,json=serviceName,proto3" json:"service_name,omitempty"`
	AgentUri      string                 `protobuf:"bytes,3,opt,name=agent_uri,json=agentUri,proto3" json:"agent_uri,omitempty"`    // URI SAN of the provider agent
	RelayId       string                 `protobuf:"bytes,4,opt,name=relay_id,json=relayId,proto3" json:"relay_id,omitempty"`       // id of the relay holding the agent's conn
	LocalAddr     string                 `protobuf:"bytes,5,opt,name=local_addr,json=localAddr,proto3" json:"local_addr,omitempty"` // informational
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterServiceRequest) Reset() {
	*x = RegisterServiceRequest{}
	mi := &file_registry_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterServiceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterServiceRequest) ProtoMessage() {}

func (x *RegisterServiceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_registry_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterServiceRequest.ProtoReflect.Descriptor instead.
func (*RegisterServiceRequest) Descriptor() ([]byte, []int) {
	return file_registry_proto_rawDescGZIP(), []int{0}
}

func (x *RegisterServiceRequest) GetTenant() string {
	if x != nil {
		return x.Tenant
	}
	return ""
}

func (x *RegisterServiceRequest) GetServiceName() string {
	if x != nil {
		return x.ServiceName
	}
	return ""
}

func (x *RegisterServiceRequest) GetAgentUri() string {
	if x != nil {
		return x.AgentUri
	}
	return ""
}

func (x *RegisterServiceRequest) GetRelayId() string {
	if x != nil {
		return x.RelayId
	}
	return ""
}

func (x *RegisterServiceRequest) GetLocalAddr() string {
	if x != nil {
		return x.LocalAddr
	}
	return ""
}

type RegisterServiceResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ServiceId     string                 `protobuf:"bytes,1,opt,name=service_id,json=serviceId,proto3" json:"service_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterServiceResponse) Reset() {
	*x = RegisterServiceResponse{}
	mi := &file_registry_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterServiceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterServiceResponse) ProtoMessage() {}

func (x *RegisterServiceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_registry_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterServiceResponse.ProtoReflect.Descriptor instead.
func (*RegisterServiceResponse) Descriptor() ([]byte, []int) {
	return file_registry_proto_rawDescGZIP(), []int{1}
}

func (x *RegisterServiceResponse) GetServiceId() string {
	if x != nil {
		return x.ServiceId
	}
	return ""
}

type DeregisterAgentRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Tenant        string                 `protobuf:"bytes,1,opt,name=tenant,proto3" json:"tenant,omitempty"`
	AgentUri      string                 `protobuf:"bytes,2,opt,name=agent_uri,json=agentUri,proto3" json:"agent_uri,omitempty"`
	RelayId       string                 `protobuf:"bytes,3,opt,name=relay_id,json=relayId,proto3" json:"relay_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeregisterAgentRequest) Reset() {
	*x = DeregisterAgentRequest{}
	mi := &file_registry_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeregisterAgentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeregisterAgentRequest) ProtoMessage() {}

func (x *DeregisterAgentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_registry_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeregisterAgentRequest.ProtoReflect.Descriptor instead.
func (*DeregisterAgentRequest) Descriptor() ([]byte, []int) {
	return file_registry_proto_rawDescGZIP(), []int{2}
}

func (x *DeregisterAgentRequest) GetTenant() string {
	if x != nil {
		return x.Tenant
	}
	return ""
}

func (x *DeregisterAgentRequest) GetAgentUri() string {
	if x != nil {
		return x.AgentUri
	}
	return ""
}

func (x *DeregisterAgentRequest) GetRelayId() string {
	if x != nil {
		return x.RelayId
	}
	return ""
}

type DeregisterAgentResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeregisterAgentResponse) Reset() {
	*x = DeregisterAgentResponse{}
	mi := &file_registry_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeregisterAgentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeregisterAgentResponse) ProtoMessage() {}

func (x *DeregisterAgentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_registry_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeregisterAgentResponse.ProtoReflect.Descriptor instead.
func (*DeregisterAgentResponse) Descriptor() ([]byte, []int) {
	return file_registry_proto_rawDescGZIP(), []int{3}
}

type ResolveRequest struct {
	state       protoimpl.MessageState `protogen:"open.v1"`
	Tenant      string                 `protobuf:"bytes,1,opt,name=tenant,proto3" json:"tenant,omitempty"`
	ServiceName string                 `protobuf:"bytes,2,opt,name=service_name,json=serviceName,proto3" json:"service_name,omitempty"`
	// caller_region is the region label of the relay that issued the
	// Resolve on behalf of a consumer agent. The controller uses it
	// to prefer providers whose relay sits in the same region —
	// multi-region deployments avoid an unnecessary cross-region
	// hop. Empty disables the preference and the first registered
	// provider wins (back-compat for single-relay deployments).
	CallerRegion  string `protobuf:"bytes,3,opt,name=caller_region,json=callerRegion,proto3" json:"caller_region,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResolveRequest) Reset() {
	*x = ResolveRequest{}
	mi := &file_registry_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResolveRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResolveRequest) ProtoMessage() {}

func (x *ResolveRequest) ProtoReflect() protoreflect.Message {
	mi := &file_registry_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResolveRequest.ProtoReflect.Descriptor instead.
func (*ResolveRequest) Descriptor() ([]byte, []int) {
	return file_registry_proto_rawDescGZIP(), []int{4}
}

func (x *ResolveRequest) GetTenant() string {
	if x != nil {
		return x.Tenant
	}
	return ""
}

func (x *ResolveRequest) GetServiceName() string {
	if x != nil {
		return x.ServiceName
	}
	return ""
}

func (x *ResolveRequest) GetCallerRegion() string {
	if x != nil {
		return x.CallerRegion
	}
	return ""
}

type Provider struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	ServiceId       string                 `protobuf:"bytes,1,opt,name=service_id,json=serviceId,proto3" json:"service_id,omitempty"`
	AgentUri        string                 `protobuf:"bytes,2,opt,name=agent_uri,json=agentUri,proto3" json:"agent_uri,omitempty"`
	RelayId         string                 `protobuf:"bytes,3,opt,name=relay_id,json=relayId,proto3" json:"relay_id,omitempty"`
	LocalAddr       string                 `protobuf:"bytes,4,opt,name=local_addr,json=localAddr,proto3" json:"local_addr,omitempty"`
	UpdatedAtUnixMs int64                  `protobuf:"varint,5,opt,name=updated_at_unix_ms,json=updatedAtUnixMs,proto3" json:"updated_at_unix_ms,omitempty"`
	// relay_endpoint is the address agents (and other relays) dial to
	// reach the relay holding this provider. Populated by the controller
	// via a JOIN with relay_instances; empty if the relay never called
	// UpsertRelay. Used by inter-relay stream forwarding.
	RelayEndpoint string `protobuf:"bytes,6,opt,name=relay_endpoint,json=relayEndpoint,proto3" json:"relay_endpoint,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Provider) Reset() {
	*x = Provider{}
	mi := &file_registry_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Provider) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Provider) ProtoMessage() {}

func (x *Provider) ProtoReflect() protoreflect.Message {
	mi := &file_registry_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Provider.ProtoReflect.Descriptor instead.
func (*Provider) Descriptor() ([]byte, []int) {
	return file_registry_proto_rawDescGZIP(), []int{5}
}

func (x *Provider) GetServiceId() string {
	if x != nil {
		return x.ServiceId
	}
	return ""
}

func (x *Provider) GetAgentUri() string {
	if x != nil {
		return x.AgentUri
	}
	return ""
}

func (x *Provider) GetRelayId() string {
	if x != nil {
		return x.RelayId
	}
	return ""
}

func (x *Provider) GetLocalAddr() string {
	if x != nil {
		return x.LocalAddr
	}
	return ""
}

func (x *Provider) GetUpdatedAtUnixMs() int64 {
	if x != nil {
		return x.UpdatedAtUnixMs
	}
	return 0
}

func (x *Provider) GetRelayEndpoint() string {
	if x != nil {
		return x.RelayEndpoint
	}
	return ""
}

type ResolveResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Providers     []*Provider            `protobuf:"bytes,1,rep,name=providers,proto3" json:"providers,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResolveResponse) Reset() {
	*x = ResolveResponse{}
	mi := &file_registry_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResolveResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResolveResponse) ProtoMessage() {}

func (x *ResolveResponse) ProtoReflect() protoreflect.Message {
	mi := &file_registry_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResolveResponse.ProtoReflect.Descriptor instead.
func (*ResolveResponse) Descriptor() ([]byte, []int) {
	return file_registry_proto_rawDescGZIP(), []int{6}
}

func (x *ResolveResponse) GetProviders() []*Provider {
	if x != nil {
		return x.Providers
	}
	return nil
}

type WatchRequest struct {
	state  protoimpl.MessageState `protogen:"open.v1"`
	Tenant string                 `protobuf:"bytes,1,opt,name=tenant,proto3" json:"tenant,omitempty"`
	// empty = all services in tenant
	ServiceNames  []string `protobuf:"bytes,2,rep,name=service_names,json=serviceNames,proto3" json:"service_names,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WatchRequest) Reset() {
	*x = WatchRequest{}
	mi := &file_registry_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WatchRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WatchRequest) ProtoMessage() {}

func (x *WatchRequest) ProtoReflect() protoreflect.Message {
	mi := &file_registry_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WatchRequest.ProtoReflect.Descriptor instead.
func (*WatchRequest) Descriptor() ([]byte, []int) {
	return file_registry_proto_rawDescGZIP(), []int{7}
}

func (x *WatchRequest) GetTenant() string {
	if x != nil {
		return x.Tenant
	}
	return ""
}

func (x *WatchRequest) GetServiceNames() []string {
	if x != nil {
		return x.ServiceNames
	}
	return nil
}

type WatchEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Kind          EventKind              `protobuf:"varint,1,opt,name=kind,proto3,enum=outrelay.control.v1.EventKind" json:"kind,omitempty"`
	Provider      *Provider              `protobuf:"bytes,2,opt,name=provider,proto3" json:"provider,omitempty"`
	ServiceName   string                 `protobuf:"bytes,3,opt,name=service_name,json=serviceName,proto3" json:"service_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WatchEvent) Reset() {
	*x = WatchEvent{}
	mi := &file_registry_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WatchEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WatchEvent) ProtoMessage() {}

func (x *WatchEvent) ProtoReflect() protoreflect.Message {
	mi := &file_registry_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WatchEvent.ProtoReflect.Descriptor instead.
func (*WatchEvent) Descriptor() ([]byte, []int) {
	return file_registry_proto_rawDescGZIP(), []int{8}
}

func (x *WatchEvent) GetKind() EventKind {
	if x != nil {
		return x.Kind
	}
	return EventKind_EVENT_KIND_UNSPECIFIED
}

func (x *WatchEvent) GetProvider() *Provider {
	if x != nil {
		return x.Provider
	}
	return nil
}

func (x *WatchEvent) GetServiceName() string {
	if x != nil {
		return x.ServiceName
	}
	return ""
}

type UpsertRelayRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Region        string                 `protobuf:"bytes,2,opt,name=region,proto3" json:"region,omitempty"`
	Endpoint      string                 `protobuf:"bytes,3,opt,name=endpoint,proto3" json:"endpoint,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpsertRelayRequest) Reset() {
	*x = UpsertRelayRequest{}
	mi := &file_registry_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpsertRelayRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpsertRelayRequest) ProtoMessage() {}

func (x *UpsertRelayRequest) ProtoReflect() protoreflect.Message {
	mi := &file_registry_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpsertRelayRequest.ProtoReflect.Descriptor instead.
func (*UpsertRelayRequest) Descriptor() ([]byte, []int) {
	return file_registry_proto_rawDescGZIP(), []int{9}
}

func (x *UpsertRelayRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UpsertRelayRequest) GetRegion() string {
	if x != nil {
		return x.Region
	}
	return ""
}

func (x *UpsertRelayRequest) GetEndpoint() string {
	if x != nil {
		return x.Endpoint
	}
	return ""
}

type UpsertRelayResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpsertRelayResponse) Reset() {
	*x = UpsertRelayResponse{}
	mi := &file_registry_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpsertRelayResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpsertRelayResponse) ProtoMessage() {}

func (x *UpsertRelayResponse) ProtoReflect() protoreflect.Message {
	mi := &file_registry_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpsertRelayResponse.ProtoReflect.Descriptor instead.
func (*UpsertRelayResponse) Descriptor() ([]byte, []int) {
	return file_registry_proto_rawDescGZIP(), []int{10}
}

var File_registry_proto protoreflect.FileDescriptor

const file_registry_proto_rawDesc = "" +
	"\n" +
	"\x0eregistry.proto\x12\x13outrelay.control.v1\"\xaa\x01\n" +
	"\x16RegisterServiceRequest\x12\x16\n" +
	"\x06tenant\x18\x01 \x01(\tR\x06tenant\x12!\n" +
	"\fservice_name\x18\x02 \x01(\tR\vserviceName\x12\x1b\n" +
	"\tagent_uri\x18\x03 \x01(\tR\bagentUri\x12\x19\n" +
	"\brelay_id\x18\x04 \x01(\tR\arelayId\x12\x1d\n" +
	"\n" +
	"local_addr\x18\x05 \x01(\tR\tlocalAddr\"8\n" +
	"\x17RegisterServiceResponse\x12\x1d\n" +
	"\n" +
	"service_id\x18\x01 \x01(\tR\tserviceId\"h\n" +
	"\x16DeregisterAgentRequest\x12\x16\n" +
	"\x06tenant\x18\x01 \x01(\tR\x06tenant\x12\x1b\n" +
	"\tagent_uri\x18\x02 \x01(\tR\bagentUri\x12\x19\n" +
	"\brelay_id\x18\x03 \x01(\tR\arelayId\"\x19\n" +
	"\x17DeregisterAgentResponse\"p\n" +
	"\x0eResolveRequest\x12\x16\n" +
	"\x06tenant\x18\x01 \x01(\tR\x06tenant\x12!\n" +
	"\fservice_name\x18\x02 \x01(\tR\vserviceName\x12#\n" +
	"\rcaller_region\x18\x03 \x01(\tR\fcallerRegion\"\xd4\x01\n" +
	"\bProvider\x12\x1d\n" +
	"\n" +
	"service_id\x18\x01 \x01(\tR\tserviceId\x12\x1b\n" +
	"\tagent_uri\x18\x02 \x01(\tR\bagentUri\x12\x19\n" +
	"\brelay_id\x18\x03 \x01(\tR\arelayId\x12\x1d\n" +
	"\n" +
	"local_addr\x18\x04 \x01(\tR\tlocalAddr\x12+\n" +
	"\x12updated_at_unix_ms\x18\x05 \x01(\x03R\x0fupdatedAtUnixMs\x12%\n" +
	"\x0erelay_endpoint\x18\x06 \x01(\tR\rrelayEndpoint\"N\n" +
	"\x0fResolveResponse\x12;\n" +
	"\tproviders\x18\x01 \x03(\v2\x1d.outrelay.control.v1.ProviderR\tproviders\"K\n" +
	"\fWatchRequest\x12\x16\n" +
	"\x06tenant\x18\x01 \x01(\tR\x06tenant\x12#\n" +
	"\rservice_names\x18\x02 \x03(\tR\fserviceNames\"\x9e\x01\n" +
	"\n" +
	"WatchEvent\x122\n" +
	"\x04kind\x18\x01 \x01(\x0e2\x1e.outrelay.control.v1.EventKindR\x04kind\x129\n" +
	"\bprovider\x18\x02 \x01(\v2\x1d.outrelay.control.v1.ProviderR\bprovider\x12!\n" +
	"\fservice_name\x18\x03 \x01(\tR\vserviceName\"X\n" +
	"\x12UpsertRelayRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x16\n" +
	"\x06region\x18\x02 \x01(\tR\x06region\x12\x1a\n" +
	"\bendpoint\x18\x03 \x01(\tR\bendpoint\"\x15\n" +
	"\x13UpsertRelayResponse*[\n" +
	"\tEventKind\x12\x1a\n" +
	"\x16EVENT_KIND_UNSPECIFIED\x10\x00\x12\x17\n" +
	"\x13EVENT_KIND_REGISTER\x10\x01\x12\x19\n" +
	"\x15EVENT_KIND_DEREGISTER\x10\x022\xed\x03\n" +
	"\bRegistry\x12l\n" +
	"\x0fRegisterService\x12+.outrelay.control.v1.RegisterServiceRequest\x1a,.outrelay.control.v1.RegisterServiceResponse\x12l\n" +
	"\x0fDeregisterAgent\x12+.outrelay.control.v1.DeregisterAgentRequest\x1a,.outrelay.control.v1.DeregisterAgentResponse\x12T\n" +
	"\aResolve\x12#.outrelay.control.v1.ResolveRequest\x1a$.outrelay.control.v1.ResolveResponse\x12M\n" +
	"\x05Watch\x12!.outrelay.control.v1.WatchRequest\x1a\x1f.outrelay.control.v1.WatchEvent0\x01\x12`\n" +
	"\vUpsertRelay\x12'.outrelay.control.v1.UpsertRelayRequest\x1a(.outrelay.control.v1.UpsertRelayResponseB6Z4github.com/boanlab/OutRelay/lib/control/v1;controlv1b\x06proto3"

var (
	file_registry_proto_rawDescOnce sync.Once
	file_registry_proto_rawDescData []byte
)

func file_registry_proto_rawDescGZIP() []byte {
	file_registry_proto_rawDescOnce.Do(func() {
		file_registry_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_registry_proto_rawDesc), len(file_registry_proto_rawDesc)))
	})
	return file_registry_proto_rawDescData
}

var file_registry_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_registry_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_registry_proto_goTypes = []any{
	(EventKind)(0),                  // 0: outrelay.control.v1.EventKind
	(*RegisterServiceRequest)(nil),  // 1: outrelay.control.v1.RegisterServiceRequest
	(*RegisterServiceResponse)(nil), // 2: outrelay.control.v1.RegisterServiceResponse
	(*DeregisterAgentRequest)(nil),  // 3: outrelay.control.v1.DeregisterAgentRequest
	(*DeregisterAgentResponse)(nil), // 4: outrelay.control.v1.DeregisterAgentResponse
	(*ResolveRequest)(nil),          // 5: outrelay.control.v1.ResolveRequest
	(*Provider)(nil),                // 6: outrelay.control.v1.Provider
	(*ResolveResponse)(nil),         // 7: outrelay.control.v1.ResolveResponse
	(*WatchRequest)(nil),            // 8: outrelay.control.v1.WatchRequest
	(*WatchEvent)(nil),              // 9: outrelay.control.v1.WatchEvent
	(*UpsertRelayRequest)(nil),      // 10: outrelay.control.v1.UpsertRelayRequest
	(*UpsertRelayResponse)(nil),     // 11: outrelay.control.v1.UpsertRelayResponse
}
var file_registry_proto_depIdxs = []int32{
	6,  // 0: outrelay.control.v1.ResolveResponse.providers:type_name -> outrelay.control.v1.Provider
	0,  // 1: outrelay.control.v1.WatchEvent.kind:type_name -> outrelay.control.v1.EventKind
	6,  // 2: outrelay.control.v1.WatchEvent.provider:type_name -> outrelay.control.v1.Provider
	1,  // 3: outrelay.control.v1.Registry.RegisterService:input_type -> outrelay.control.v1.RegisterServiceRequest
	3,  // 4: outrelay.control.v1.Registry.DeregisterAgent:input_type -> outrelay.control.v1.DeregisterAgentRequest
	5,  // 5: outrelay.control.v1.Registry.Resolve:input_type -> outrelay.control.v1.ResolveRequest
	8,  // 6: outrelay.control.v1.Registry.Watch:input_type -> outrelay.control.v1.WatchRequest
	10, // 7: outrelay.control.v1.Registry.UpsertRelay:input_type -> outrelay.control.v1.UpsertRelayRequest
	2,  // 8: outrelay.control.v1.Registry.RegisterService:output_type -> outrelay.control.v1.RegisterServiceResponse
	4,  // 9: outrelay.control.v1.Registry.DeregisterAgent:output_type -> outrelay.control.v1.DeregisterAgentResponse
	7,  // 10: outrelay.control.v1.Registry.Resolve:output_type -> outrelay.control.v1.ResolveResponse
	9,  // 11: outrelay.control.v1.Registry.Watch:output_type -> outrelay.control.v1.WatchEvent
	11, // 12: outrelay.control.v1.Registry.UpsertRelay:output_type -> outrelay.control.v1.UpsertRelayResponse
	8,  // [8:13] is the sub-list for method output_type
	3,  // [3:8] is the sub-list for method input_type
	3,  // [3:3] is the sub-list for extension type_name
	3,  // [3:3] is the sub-list for extension extendee
	0,  // [0:3] is the sub-list for field type_name
}

func init() { file_registry_proto_init() }
func file_registry_proto_init() {
	if File_registry_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_registry_proto_rawDesc), len(file_registry_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_registry_proto_goTypes,
		DependencyIndexes: file_registry_proto_depIdxs,
		EnumInfos:         file_registry_proto_enumTypes,
		MessageInfos:      file_registry_proto_msgTypes,
	}.Build()
	File_registry_proto = out.File
	file_registry_proto_goTypes = nil
	file_registry_proto_depIdxs = nil
}
