// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: orp.proto

package orpv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// FrameTypeHello (0x001) — agent -> relay.
type Hello struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	ProtocolVersion string                 `protobuf:"bytes,1,opt,name=protocol_version,json=protocolVersion,proto3" json:"protocol_version,omitempty"` // "orp/1"
	AgentUri        string                 `protobuf:"bytes,2,opt,name=agent_uri,json=agentUri,proto3" json:"agent_uri,omitempty"`                      // identity URI from cert SAN, e.g. outrelay://acme/agent/<uuid>
	Capabilities    []string               `protobuf:"bytes,3,rep,name=capabilities,proto3" json:"capabilities,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *Hello) Reset() {
	*x = Hello{}
	mi := &file_orp_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Hello) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Hello) ProtoMessage() {}

func (x *Hello) ProtoReflect() protoreflect.Message {
	mi := &file_orp_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Hello.ProtoReflect.Descriptor instead.
func (*Hello) Descriptor() ([]byte, []int) {
	return file_orp_proto_rawDescGZIP(), []int{0}
}

func (x *Hello) GetProtocolVersion() string {
	if x != nil {
		return x.ProtocolVersion
	}
	return ""
}

func (x *Hello) GetAgentUri() string {
	if x != nil {
		return x.AgentUri
	}
	return ""
}

func (x *Hello) GetCapabilities() []string {
	if x != nil {
		return x.Capabilities
	}
	return nil
}

// FrameTypeHelloAck (0x002) — relay -> agent.
type HelloAck struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	SessionId        string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	ServerTimeUnixMs int64                  `protobuf:"varint,2,opt,name=server_time_unix_ms,json=serverTimeUnixMs,proto3" json:"server_time_unix_ms,omitempty"`
	AcceptedFeatures []string               `protobuf:"bytes,3,rep,name=accepted_features,json=acceptedFeatures,proto3" json:"accepted_features,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *HelloAck) Reset() {
	*x = HelloAck{}
	mi := &file_orp_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HelloAck) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HelloAck) ProtoMessage() {}

func (x *HelloAck) ProtoReflect() protoreflect.Message {
	mi := &file_orp_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HelloAck.ProtoReflect.Descriptor instead.
func (*HelloAck) Descriptor() ([]byte, []int) {
	return file_orp_proto_rawDescGZIP(), []int{1}
}

func (x *HelloAck) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *HelloAck) GetServerTimeUnixMs() int64 {
	if x != nil {
		return x.ServerTimeUnixMs
	}
	return 0
}

func (x *HelloAck) GetAcceptedFeatures() []string {
	if x != nil {
		return x.AcceptedFeatures
	}
	return nil
}

// FrameTypeRegister (0x003) — agent -> relay.
//
// The agent declares it provides service_name. local_addr is purely
// informational (the agent dials its own local backend when it
// receives INCOMING_STREAM, never the relay).
type Register struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ServiceName   string                 `protobuf:"bytes,1,opt,name=service_name,json=serviceName,proto3" json:"service_name,omitempty"`
	LocalAddr     string                 `protobuf:"bytes,2,opt,name=local_addr,json=localAddr,proto3" json:"local_addr,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Register) Reset() {
	*x = Register{}
	mi := &file_orp_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Register) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Register) ProtoMessage() {}

func (x *Register) ProtoReflect() protoreflect.Message {
	mi := &file_orp_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Register.ProtoReflect.Descriptor instead.
func (*Register) Descriptor() ([]byte, []int) {
	return file_orp_proto_rawDescGZIP(), []int{2}
}

func (x *Register) GetServiceName() string {
	if x != nil {
		return x.ServiceName
	}
	return ""
}

func (x *Register) GetLocalAddr() string {
	if x != nil {
		return x.LocalAddr
	}
	return ""
}

// FrameTypeRegisterAck (0x004) — relay -> agent.
type RegisterAck struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ServiceId     string                 `protobuf:"bytes,1,opt,name=service_id,json=serviceId,proto3" json:"service_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterAck) Reset() {
	*x = RegisterAck{}
	mi := &file_orp_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterAck) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterAck) ProtoMessage() {}

func (x *RegisterAck) ProtoReflect() protoreflect.Message {
	mi := &file_orp_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterAck.ProtoReflect.Descriptor instead.
func (*RegisterAck) Descriptor() ([]byte, []int) {
	return file_orp_proto_rawDescGZIP(), []int{3}
}

func (x *RegisterAck) GetServiceId() string {
	if x != nil {
		return x.ServiceId
	}
	return ""
}

// FrameTypeOpenStream (0x010) — consumer-side agent -> relay.
//
// Sent on a freshly opened QUIC stream; the same stream becomes the
// data carrier after the relay enters splice mode. stream_id is the
// 64-bit identifier that follows this stream across relay failover
// and across P2P promotion / demotion. The consumer-side agent
// generates it.
type OpenStream struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TargetService string                 `protobuf:"bytes,1,opt,name=target_service,json=targetService,proto3" json:"target_service,omitempty"`
	Method        string                 `protobuf:"bytes,2,opt,name=method,proto3" json:"method,omitempty"` // optional; e.g. "POST /charge"
	StreamId      uint64                 `protobuf:"varint,3,opt,name=stream_id,json=streamId,proto3" json:"stream_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OpenStream) Reset() {
	*x = OpenStream{}
	mi := &file_orp_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OpenStream) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OpenStream) ProtoMessage() {}

func (x *OpenStream) ProtoReflect() protoreflect.Message {
	mi := &file_orp_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OpenStream.ProtoReflect.Descriptor instead.
func (*OpenStream) Descriptor() ([]byte, []int) {
	return file_orp_proto_rawDescGZIP(), []int{4}
}

func (x *OpenStream) GetTargetService() string {
	if x != nil {
		return x.TargetService
	}
	return ""
}

func (x *OpenStream) GetMethod() string {
	if x != nil {
		return x.Method
	}
	return ""
}

func (x *OpenStream) GetStreamId() uint64 {
	if x != nil {
		return x.StreamId
	}
	return 0
}

// FrameTypeIncomingStream (0x011) — relay -> provider-side agent.
//
// Sent on a fresh QUIC stream opened by the relay toward the provider.
// The provider responds with STREAM_ACCEPT or STREAM_REJECT on the
// same stream. stream_id mirrors OpenStream so both ends agree.
type IncomingStream struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	TargetService  string                 `protobuf:"bytes,1,opt,name=target_service,json=targetService,proto3" json:"target_service,omitempty"`
	Method         string                 `protobuf:"bytes,2,opt,name=method,proto3" json:"method,omitempty"`
	SourceAgentUri string                 `protobuf:"bytes,3,opt,name=source_agent_uri,json=sourceAgentUri,proto3" json:"source_agent_uri,omitempty"` // caller identity for policy / audit
	StreamId       uint64                 `protobuf:"varint,4,opt,name=stream_id,json=streamId,proto3" json:"stream_id,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *IncomingStream) Reset() {
	*x = IncomingStream{}
	mi := &file_orp_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IncomingStream) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IncomingStream) ProtoMessage() {}

func (x *IncomingStream) ProtoReflect() protoreflect.Message {
	mi := &file_orp_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IncomingStream.ProtoReflect.Descriptor instead.
func (*IncomingStream) Descriptor() ([]byte, []int) {
	return file_orp_proto_rawDescGZIP(), []int{5}
}

func (x *IncomingStream) GetTargetService() string {
	if x != nil {
		return x.TargetService
	}
	return ""
}

func (x *IncomingStream) GetMethod() string {
	if x != nil {
		return x.Method
	}
	return ""
}

func (x *IncomingStream) GetSourceAgentUri() string {
	if x != nil {
		return x.SourceAgentUri
	}
	return ""
}

func (x *IncomingStream) GetStreamId() uint64 {
	if x != nil {
		return x.StreamId
	}
	return 0
}

// FrameTypeStreamCheckpoint (0x110) — agent -> agent (relay forwards).
//
// Periodically (default 100ms) each agent sends a checkpoint on its
// control stream. my_position is the count of bytes the agent has
// written into the data stream; peer_ack_position is the count of
// bytes the agent has consumed from its peer, so the peer can free
// its ring buffer up to that offset.
type StreamCheckpoint struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	StreamId        uint64                 `protobuf:"varint,1,opt,name=stream_id,json=streamId,proto3" json:"stream_id,omitempty"`
	MyPosition      uint64                 `protobuf:"varint,2,opt,name=my_position,json=myPosition,proto3" json:"my_position,omitempty"`
	PeerAckPosition uint64                 `protobuf:"varint,3,opt,name=peer_ack_position,json=peerAckPosition,proto3" json:"peer_ack_position,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *StreamCheckpoint) Reset() {
	*x = StreamCheckpoint{}
	mi := &file_orp_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreamCheckpoint) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamCheckpoint) ProtoMessage() {}

func (x *StreamCheckpoint) ProtoReflect() protoreflect.Message {
	mi := &file_orp_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamCheckpoint.ProtoReflect.Descriptor instead.
func (*StreamCheckpoint) Descriptor() ([]byte, []int) {
	return file_orp_proto_rawDescGZIP(), []int{6}
}

func (x *StreamCheckpoint) GetStreamId() uint64 {
	if x != nil {
		return x.StreamId
	}
	return 0
}

func (x *StreamCheckpoint) GetMyPosition() uint64 {
	if x != nil {
		return x.MyPosition
	}
	return 0
}

func (x *StreamCheckpoint) GetPeerAckPosition() uint64 {
	if x != nil {
		return x.PeerAckPosition
	}
	return 0
}

// FrameTypeStreamResume (0x111) — agent -> relay (after reconnect).
//
// After detecting a relay-side disconnect, both agents reconnect and
// emit STREAM_RESUME on a fresh stream for every stream that was
// in flight. The receiving relay buckets these by stream_id with a
// 5-second window; once both halves arrive, the relay splices them
// and each agent retransmits bytes (peer.peer_ack_position,
// my.my_position] from its ring buffer.
type StreamResume struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	StreamId        uint64                 `protobuf:"varint,1,opt,name=stream_id,json=streamId,proto3" json:"stream_id,omitempty"`
	MyPosition      uint64                 `protobuf:"varint,2,opt,name=my_position,json=myPosition,proto3" json:"my_position,omitempty"`
	PeerAckPosition uint64                 `protobuf:"varint,3,opt,name=peer_ack_position,json=peerAckPosition,proto3" json:"peer_ack_position,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *StreamResume) Reset() {
	*x = StreamResume{}
	mi := &file_orp_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreamResume) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamResume) ProtoMessage() {}

func (x *StreamResume) ProtoReflect() protoreflect.Message {
	mi := &file_orp_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamResume.ProtoReflect.Descriptor instead.
func (*StreamResume) Descriptor() ([]byte, []int) {
	return file_orp_proto_rawDescGZIP(), []int{7}
}

func (x *StreamResume) GetStreamId() uint64 {
	if x != nil {
		return x.StreamId
	}
	return 0
}

func (x *StreamResume) GetMyPosition() uint64 {
	if x != nil {
		return x.MyPosition
	}
	return 0
}

func (x *StreamResume) GetPeerAckPosition() uint64 {
	if x != nil {
		return x.PeerAckPosition
	}
	return 0
}

// FrameTypeObservedAddrQuery (0x120) — agent -> relay.
// Sent on the agent's control stream. The relay replies with
// OBSERVED_ADDR_RESP carrying the agent's NAT-mapped src ip:port.
// Effectively a built-in STUN: the relay already terminates every
// agent's outbound conn so it knows the public mapping.
type ObservedAddrQuery struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// request_id is echoed in the response so an agent can match
	// outstanding queries.
	RequestId     uint64 `protobuf:"varint,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ObservedAddrQuery) Reset() {
	*x = ObservedAddrQuery{}
	mi := &file_orp_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ObservedAddrQuery) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ObservedAddrQuery) ProtoMessage() {}

func (x *ObservedAddrQuery) ProtoReflect() protoreflect.Message {
	mi := &file_orp_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ObservedAddrQuery.ProtoReflect.Descriptor instead.
func (*ObservedAddrQuery) Descriptor() ([]byte, []int) {
	return file_orp_proto_rawDescGZIP(), []int{8}
}

func (x *ObservedAddrQuery) GetRequestId() uint64 {
	if x != nil {
		return x.RequestId
	}
	return 0
}

// FrameTypeObservedAddrResp (0x121) — relay -> agent.
type ObservedAddrResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RequestId     uint64                 `protobuf:"varint,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	Ip            string                 `protobuf:"bytes,2,opt,name=ip,proto3" json:"ip,omitempty"`
	Port          uint32                 `protobuf:"varint,3,opt,name=port,proto3" json:"port,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ObservedAddrResp) Reset() {
	*x = ObservedAddrResp{}
	mi := &file_orp_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ObservedAddrResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ObservedAddrResp) ProtoMessage() {}

func (x *ObservedAddrResp) ProtoReflect() protoreflect.Message {
	mi := &file_orp_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ObservedAddrResp.ProtoReflect.Descriptor instead.
func (*ObservedAddrResp) Descriptor() ([]byte, []int) {
	return file_orp_proto_rawDescGZIP(), []int{9}
}

func (x *ObservedAddrResp) GetRequestId() uint64 {
	if x != nil {
		return x.RequestId
	}
	return 0
}

func (x *ObservedAddrResp) GetIp() string {
	if x != nil {
		return x.Ip
	}
	return ""
}

func (x *ObservedAddrResp) GetPort() uint32 {
	if x != nil {
		return x.Port
	}
	return 0
}

// Candidate is one possible address an agent can be reached at.
// kind reflects RFC 8445 with a simplified label set: "host" is a
// local interface address, "srflx" is the OBSERVED_ADDR_RESP value
// (server-reflexive). "relay" is the existing relay endpoint and is
// already known both sides; we don't include it here.
type Candidate struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Kind          string                 `protobuf:"bytes,1,opt,name=kind,proto3" json:"kind,omitempty"` // "host" | "srflx"
	Ip            string                 `protobuf:"bytes,2,opt,name=ip,proto3" json:"ip,omitempty"`
	Port          uint32                 `protobuf:"varint,3,opt,name=port,proto3" json:"port,omitempty"`
	Priority      uint32                 `protobuf:"varint,4,opt,name=priority,proto3" json:"priority,omitempty"` // higher = prefer first
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Candidate) Reset() {
	*x = Candidate{}
	mi := &file_orp_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Candidate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Candidate) ProtoMessage() {}

func (x *Candidate) ProtoReflect() protoreflect.Message {
	mi := &file_orp_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Candidate.ProtoReflect.Descriptor instead.
func (*Candidate) Descriptor() ([]byte, []int) {
	return file_orp_proto_rawDescGZIP(), []int{10}
}

func (x *Candidate) GetKind() string {
	if x != nil {
		return x.Kind
	}
	return ""
}

func (x *Candidate) GetIp() string {
	if x != nil {
		return x.Ip
	}
	return ""
}

func (x *Candidate) GetPort() uint32 {
	if x != nil {
		return x.Port
	}
	return 0
}

func (x *Candidate) GetPriority() uint32 {
	if x != nil {
		return x.Priority
	}
	return 0
}

// FrameTypeCandidateOffer (0x122) — agent -> relay (forwarded to peer).
// Sent on a per-stream control stream. The agent has finished
// gathering candidates and offers them to the peer via the relay.
type CandidateOffer struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StreamId      uint64                 `protobuf:"varint,1,opt,name=stream_id,json=streamId,proto3" json:"stream_id,omitempty"`
	Candidates    []*Candidate           `protobuf:"bytes,2,rep,name=candidates,proto3" json:"candidates,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CandidateOffer) Reset() {
	*x = CandidateOffer{}
	mi := &file_orp_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CandidateOffer) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CandidateOffer) ProtoMessage() {}

func (x *CandidateOffer) ProtoReflect() protoreflect.Message {
	mi := &file_orp_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CandidateOffer.ProtoReflect.Descriptor instead.
func (*CandidateOffer) Descriptor() ([]byte, []int) {
	return file_orp_proto_rawDescGZIP(), []int{11}
}

func (x *CandidateOffer) GetStreamId() uint64 {
	if x != nil {
		return x.StreamId
	}
	return 0
}

func (x *CandidateOffer) GetCandidates() []*Candidate {
	if x != nil {
		return x.Candidates
	}
	return nil
}

// FrameTypeCandidateAnswer (0x123) — agent -> relay (forwarded to peer).
// The peer replies with its own candidate set.
type CandidateAnswer struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StreamId      uint64                 `protobuf:"varint,1,opt,name=stream_id,json=streamId,proto3" json:"stream_id,omitempty"`
	Candidates    []*Candidate           `protobuf:"bytes,2,rep,name=candidates,proto3" json:"candidates,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CandidateAnswer) Reset() {
	*x = CandidateAnswer{}
	mi := &file_orp_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CandidateAnswer) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CandidateAnswer) ProtoMessage() {}

func (x *CandidateAnswer) ProtoReflect() protoreflect.Message {
	mi := &file_orp_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CandidateAnswer.ProtoReflect.Descriptor instead.
func (*CandidateAnswer) Descriptor() ([]byte, []int) {
	return file_orp_proto_rawDescGZIP(), []int{12}
}

func (x *CandidateAnswer) GetStreamId() uint64 {
	if x != nil {
		return x.StreamId
	}
	return 0
}

func (x *CandidateAnswer) GetCandidates() []*Candidate {
	if x != nil {
		return x.Candidates
	}
	return nil
}

// FrameTypeMigrateToP2P (0x124) — both agents simultaneously to relay.
// After connectivity check selects a working candidate pair, each
// agent sends MIGRATE_TO_P2P on the in-flight stream's QUIC stream.
// The relay closes the splice; each side opens a new direct QUIC
// connection at the negotiated endpoint, and the in-flight stream
// is resumed across the new path using STREAM_RESUME semantics.
type MigrateToP2P struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	StreamId        uint64                 `protobuf:"varint,1,opt,name=stream_id,json=streamId,proto3" json:"stream_id,omitempty"`
	MyPosition      uint64                 `protobuf:"varint,2,opt,name=my_position,json=myPosition,proto3" json:"my_position,omitempty"`
	PeerAckPosition uint64                 `protobuf:"varint,3,opt,name=peer_ack_position,json=peerAckPosition,proto3" json:"peer_ack_position,omitempty"`
	Selected        *Candidate             `protobuf:"bytes,4,opt,name=selected,proto3" json:"selected,omitempty"` // the pair selected as the data path
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *MigrateToP2P) Reset() {
	*x = MigrateToP2P{}
	mi := &file_orp_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MigrateToP2P) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MigrateToP2P) ProtoMessage() {}

func (x *MigrateToP2P) ProtoReflect() protoreflect.Message {
	mi := &file_orp_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MigrateToP2P.ProtoReflect.Descriptor instead.
func (*MigrateToP2P) Descriptor() ([]byte, []int) {
	return file_orp_proto_rawDescGZIP(), []int{13}
}

func (x *MigrateToP2P) GetStreamId() uint64 {
	if x != nil {
		return x.StreamId
	}
	return 0
}

func (x *MigrateToP2P) GetMyPosition() uint64 {
	if x != nil {
		return x.MyPosition
	}
	return 0
}

func (x *MigrateToP2P) GetPeerAckPosition() uint64 {
	if x != nil {
		return x.PeerAckPosition
	}
	return 0
}

func (x *MigrateToP2P) GetSelected() *Candidate {
	if x != nil {
		return x.Selected
	}
	return nil
}

// FrameTypeMigrateToRelay (0x125) — agent -> relay (after P2P degrades).
// On RTT timeout / loss spike, agents fall back to the relay path.
// The relay restores the splice from its short-lived LRU cache.
type MigrateToRelay struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	StreamId        uint64                 `protobuf:"varint,1,opt,name=stream_id,json=streamId,proto3" json:"stream_id,omitempty"`
	MyPosition      uint64                 `protobuf:"varint,2,opt,name=my_position,json=myPosition,proto3" json:"my_position,omitempty"`
	PeerAckPosition uint64                 `protobuf:"varint,3,opt,name=peer_ack_position,json=peerAckPosition,proto3" json:"peer_ack_position,omitempty"`
	Reason          string                 `protobuf:"bytes,4,opt,name=reason,proto3" json:"reason,omitempty"` // "rtt_timeout" | "loss_threshold" | "peer_close"
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *MigrateToRelay) Reset() {
	*x = MigrateToRelay{}
	mi := &file_orp_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MigrateToRelay) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MigrateToRelay) ProtoMessage() {}

func (x *MigrateToRelay) ProtoReflect() protoreflect.Message {
	mi := &file_orp_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MigrateToRelay.ProtoReflect.Descriptor instead.
func (*MigrateToRelay) Descriptor() ([]byte, []int) {
	return file_orp_proto_rawDescGZIP(), []int{14}
}

func (x *MigrateToRelay) GetStreamId() uint64 {
	if x != nil {
		return x.StreamId
	}
	return 0
}

func (x *MigrateToRelay) GetMyPosition() uint64 {
	if x != nil {
		return x.MyPosition
	}
	return 0
}

func (x *MigrateToRelay) GetPeerAckPosition() uint64 {
	if x != nil {
		return x.PeerAckPosition
	}
	return 0
}

func (x *MigrateToRelay) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

// FrameTypeStreamAccept (0x012) — provider-side agent -> relay.
type StreamAccept struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StreamAccept) Reset() {
	*x = StreamAccept{}
	mi := &file_orp_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreamAccept) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamAccept) ProtoMessage() {}

func (x *StreamAccept) ProtoReflect() protoreflect.Message {
	mi := &file_orp_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamAccept.ProtoReflect.Descriptor instead.
func (*StreamAccept) Descriptor() ([]byte, []int) {
	return file_orp_proto_rawDescGZIP(), []int{15}
}

// FrameTypeStreamReject (0x013) — provider-side agent -> relay.
type StreamReject struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          uint32                 `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Reason        string                 `protobuf:"bytes,2,opt,name=reason,proto3" json:"reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StreamReject) Reset() {
	*x = StreamReject{}
	mi := &file_orp_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreamReject) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamReject) ProtoMessage() {}

func (x *StreamReject) ProtoReflect() protoreflect.Message {
	mi := &file_orp_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamReject.ProtoReflect.Descriptor instead.
func (*StreamReject) Descriptor() ([]byte, []int) {
	return file_orp_proto_rawDescGZIP(), []int{16}
}

func (x *StreamReject) GetCode() uint32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *StreamReject) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

// FrameTypeAllocGranted (0x151) — relay -> agent (control stream).
// Sent when policy resolves to relay_mode=forward. Tells the agent
// its own allocation_id, the peer's allocation_id (the prefix it
// must put on outbound packets), and the relay's UDP forwarding
// endpoint (host:port). The agent then opens a UDP socket to that
// endpoint, sends a registration packet, and runs end-to-end QUIC
// over the resulting path. See StreamReady below — every stream
// open produces exactly one of {StreamReady, AllocGranted}.
type AllocGranted struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	StreamId        uint64                 `protobuf:"varint,1,opt,name=stream_id,json=streamId,proto3" json:"stream_id,omitempty"`
	MyAllocation    uint32                 `protobuf:"varint,2,opt,name=my_allocation,json=myAllocation,proto3" json:"my_allocation,omitempty"`
	PeerAllocation  uint32                 `protobuf:"varint,3,opt,name=peer_allocation,json=peerAllocation,proto3" json:"peer_allocation,omitempty"`
	ForwardEndpoint string                 `protobuf:"bytes,4,opt,name=forward_endpoint,json=forwardEndpoint,proto3" json:"forward_endpoint,omitempty"` // host:port the agent sends UDP to
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *AllocGranted) Reset() {
	*x = AllocGranted{}
	mi := &file_orp_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AllocGranted) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AllocGranted) ProtoMessage() {}

func (x *AllocGranted) ProtoReflect() protoreflect.Message {
	mi := &file_orp_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AllocGranted.ProtoReflect.Descriptor instead.
func (*AllocGranted) Descriptor() ([]byte, []int) {
	return file_orp_proto_rawDescGZIP(), []int{17}
}

func (x *AllocGranted) GetStreamId() uint64 {
	if x != nil {
		return x.StreamId
	}
	return 0
}

func (x *AllocGranted) GetMyAllocation() uint32 {
	if x != nil {
		return x.MyAllocation
	}
	return 0
}

func (x *AllocGranted) GetPeerAllocation() uint32 {
	if x != nil {
		return x.PeerAllocation
	}
	return 0
}

func (x *AllocGranted) GetForwardEndpoint() string {
	if x != nil {
		return x.ForwardEndpoint
	}
	return ""
}

// FrameTypeStreamReady (0x152) — relay -> agent (control stream).
// Sent when policy resolves to relay_mode=splice, right before the
// relay starts splicing. Tells the agent the relay-mediated data
// path is up, so it can stop waiting on AllocGranted and bridge
// bytes on the data stream.
type StreamReady struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StreamId      uint64                 `protobuf:"varint,1,opt,name=stream_id,json=streamId,proto3" json:"stream_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StreamReady) Reset() {
	*x = StreamReady{}
	mi := &file_orp_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreamReady) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamReady) ProtoMessage() {}

func (x *StreamReady) ProtoReflect() protoreflect.Message {
	mi := &file_orp_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamReady.ProtoReflect.Descriptor instead.
func (*StreamReady) Descriptor() ([]byte, []int) {
	return file_orp_proto_rawDescGZIP(), []int{18}
}

func (x *StreamReady) GetStreamId() uint64 {
	if x != nil {
		return x.StreamId
	}
	return 0
}

var File_orp_proto protoreflect.FileDescriptor

const file_orp_proto_rawDesc = "" +
	"\n" +
	"\torp.proto\x12\x0foutrelay.orp.v1\"s\n" +
	"\x05Hello\x12)\n" +
	"\x10protocol_version\x18\x01 \x01(\tR\x0fprotocolVersion\x12\x1b\n" +
	"\tagent_uri\x18\x02 \x01(\tR\bagentUri\x12\"\n" +
	"\fcapabilities\x18\x03 \x03(\tR\fcapabilities\"\x85\x01\n" +
	"\bHelloAck\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12-\n" +
	"\x13server_time_unix_ms\x18\x02 \x01(\x03R\x10serverTimeUnixMs\x12+\n" +
	"\x11accepted_features\x18\x03 \x03(\tR\x10acceptedFeatures\"L\n" +
	"\bRegister\x12!\n" +
	"\fservice_name\x18\x01 \x01(\tR\vserviceName\x12\x1d\n" +
	"\n" +
	"local_addr\x18\x02 \x01(\tR\tlocalAddr\",\n" +
	"\vRegisterAck\x12\x1d\n" +
	"\n" +
	"service_id\x18\x01 \x01(\tR\tserviceId\"h\n" +
	"\n" +
	"OpenStream\x12%\n" +
	"\x0etarget_service\x18\x01 \x01(\tR\rtargetService\x12\x16\n" +
	"\x06method\x18\x02 \x01(\tR\x06method\x12\x1b\n" +
	"\tstream_id\x18\x03 \x01(\x04R\bstreamId\"\x96\x01\n" +
	"\x0eIncomingStream\x12%\n" +
	"\x0etarget_service\x18\x01 \x01(\tR\rtargetService\x12\x16\n" +
	"\x06method\x18\x02 \x01(\tR\x06method\x12(\n" +
	"\x10source_agent_uri\x18\x03 \x01(\tR\x0esourceAgentUri\x12\x1b\n" +
	"\tstream_id\x18\x04 \x01(\x04R\bstreamId\"|\n" +
	"\x10StreamCheckpoint\x12\x1b\n" +
	"\tstream_id\x18\x01 \x01(\x04R\bstreamId\x12\x1f\n" +
	"\vmy_position\x18\x02 \x01(\x04R\n" +
	"myPosition\x12*\n" +
	"\x11peer_ack_position\x18\x03 \x01(\x04R\x0fpeerAckPosition\"x\n" +
	"\fStreamResume\x12\x1b\n" +
	"\tstream_id\x18\x01 \x01(\x04R\bstreamId\x12\x1f\n" +
	"\vmy_position\x18\x02 \x01(\x04R\n" +
	"myPosition\x12*\n" +
	"\x11peer_ack_position\x18\x03 \x01(\x04R\x0fpeerAckPosition\"2\n" +
	"\x11ObservedAddrQuery\x12\x1d\n" +
	"\n" +
	"request_id\x18\x01 \x01(\x04R\trequestId\"U\n" +
	"\x10ObservedAddrResp\x12\x1d\n" +
	"\n" +
	"request_id\x18\x01 \x01(\x04R\trequestId\x12\x0e\n" +
	"\x02ip\x18\x02 \x01(\tR\x02ip\x12\x12\n" +
	"\x04port\x18\x03 \x01(\rR\x04port\"_\n" +
	"\tCandidate\x12\x12\n" +
	"\x04kind\x18\x01 \x01(\tR\x04kind\x12\x0e\n" +
	"\x02ip\x18\x02 \x01(\tR\x02ip\x12\x12\n" +
	"\x04port\x18\x03 \x01(\rR\x04port\x12\x1a\n" +
	"\bpriority\x18\x04 \x01(\rR\bpriority\"i\n" +
	"\x0eCandidateOffer\x12\x1b\n" +
	"\tstream_id\x18\x01 \x01(\x04R\bstreamId\x12:\n" +
	"\n" +
	"candidates\x18\x02 \x03(\v2\x1a.outrelay.orp.v1.CandidateR\n" +
	"candidates\"j\n" +
	"\x0fCandidateAnswer\x12\x1b\n" +
	"\tstream_id\x18\x01 \x01(\x04R\bstreamId\x12:\n" +
	"\n" +
	"candidates\x18\x02 \x03(\v2\x1a.outrelay.orp.v1.CandidateR\n" +
	"candidates\"\xb0\x01\n" +
	"\fMigrateToP2P\x12\x1b\n" +
	"\tstream_id\x18\x01 \x01(\x04R\bstreamId\x12\x1f\n" +
	"\vmy_position\x18\x02 \x01(\x04R\n" +
	"myPosition\x12*\n" +
	"\x11peer_ack_position\x18\x03 \x01(\x04R\x0fpeerAckPosition\x126\n" +
	"\bselected\x18\x04 \x01(\v2\x1a.outrelay.orp.v1.CandidateR\bselected\"\x92\x01\n" +
	"\x0eMigrateToRelay\x12\x1b\n" +
	"\tstream_id\x18\x01 \x01(\x04R\bstreamId\x12\x1f\n" +
	"\vmy_position\x18\x02 \x01(\x04R\n" +
	"myPosition\x12*\n" +
	"\x11peer_ack_position\x18\x03 \x01(\x04R\x0fpeerAckPosition\x12\x16\n" +
	"\x06reason\x18\x04 \x01(\tR\x06reason\"\x0e\n" +
	"\fStreamAccept\":\n" +
	"\fStreamReject\x12\x12\n" +
	"\x04code\x18\x01 \x01(\rR\x04code\x12\x16\n" +
	"\x06reason\x18\x02 \x01(\tR\x06reason\"\xa4\x01\n" +
	"\fAllocGranted\x12\x1b\n" +
	"\tstream_id\x18\x01 \x01(\x04R\bstreamId\x12#\n" +
	"\rmy_allocation\x18\x02 \x01(\rR\fmyAllocation\x12'\n" +
	"\x0fpeer_allocation\x18\x03 \x01(\rR\x0epeerAllocation\x12)\n" +
	"\x10forward_endpoint\x18\x04 \x01(\tR\x0fforwardEndpoint\"*\n" +
	"\vStreamReady\x12\x1b\n" +
	"\tstream_id\x18\x01 \x01(\x04R\bstreamIdB.Z,github.com/boanlab/OutRelay/lib/orp/v1;orpv1b\x06proto3"

var (
	file_orp_proto_rawDescOnce sync.Once
	file_orp_proto_rawDescData []byte
)

func file_orp_proto_rawDescGZIP() []byte {
	file_orp_proto_rawDescOnce.Do(func() {
		file_orp_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_orp_proto_rawDesc), len(file_orp_proto_rawDesc)))
	})
	return file_orp_proto_rawDescData
}

var file_orp_proto_msgTypes = make([]protoimpl.MessageInfo, 19)
var file_orp_proto_goTypes = []any{
	(*Hello)(nil),             // 0: outrelay.orp.v1.Hello
	(*HelloAck)(nil),          // 1: outrelay.orp.v1.HelloAck
	(*Register)(nil),          // 2: outrelay.orp.v1.Register
	(*RegisterAck)(nil),       // 3: outrelay.orp.v1.RegisterAck
	(*OpenStream)(nil),        // 4: outrelay.orp.v1.OpenStream
	(*IncomingStream)(nil),    // 5: outrelay.orp.v1.IncomingStream
	(*StreamCheckpoint)(nil),  // 6: outrelay.orp.v1.StreamCheckpoint
	(*StreamResume)(nil),      // 7: outrelay.orp.v1.StreamResume
	(*ObservedAddrQuery)(nil), // 8: outrelay.orp.v1.ObservedAddrQuery
	(*ObservedAddrResp)(nil),  // 9: outrelay.orp.v1.ObservedAddrResp
	(*Candidate)(nil),         // 10: outrelay.orp.v1.Candidate
	(*CandidateOffer)(nil),    // 11: outrelay.orp.v1.CandidateOffer
	(*CandidateAnswer)(nil),   // 12: outrelay.orp.v1.CandidateAnswer
	(*MigrateToP2P)(nil),      // 13: outrelay.orp.v1.MigrateToP2P
	(*MigrateToRelay)(nil),    // 14: outrelay.orp.v1.MigrateToRelay
	(*StreamAccept)(nil),      // 15: outrelay.orp.v1.StreamAccept
	(*StreamReject)(nil),      // 16: outrelay.orp.v1.StreamReject
	(*AllocGranted)(nil),      // 17: outrelay.orp.v1.AllocGranted
	(*StreamReady)(nil),       // 18: outrelay.orp.v1.StreamReady
}
var file_orp_proto_depIdxs = []int32{
	10, // 0: outrelay.orp.v1.CandidateOffer.candidates:type_name -> outrelay.orp.v1.Candidate
	10, // 1: outrelay.orp.v1.CandidateAnswer.candidates:type_name -> outrelay.orp.v1.Candidate
	10, // 2: outrelay.orp.v1.MigrateToP2P.selected:type_name -> outrelay.orp.v1.Candidate
	3,  // [3:3] is the sub-list for method output_type
	3,  // [3:3] is the sub-list for method input_type
	3,  // [3:3] is the sub-list for extension type_name
	3,  // [3:3] is the sub-list for extension extendee
	0,  // [0:3] is the sub-list for field type_name
}

func init() { file_orp_proto_init() }
func file_orp_proto_init() {
	if File_orp_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_orp_proto_rawDesc), len(file_orp_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   19,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_orp_proto_goTypes,
		DependencyIndexes: file_orp_proto_depIdxs,
		MessageInfos:      file_orp_proto_msgTypes,
	}.Build()
	File_orp_proto = out.File
	file_orp_proto_goTypes = nil
	file_orp_proto_depIdxs = nil
}
